Algoritmo "Media"


Var

  nome1, nome2 : caractere
idade1, idade2 : inteiro
media :real


Inicio
escreval("Digite o nome da Primeira pessoa")
escreva("Nome:")
leia(nome1)
escreva("Idade:")
leia(idade1)

Escreva("Dados da segunda pessoa")
escreval("Nome:")
leia(nome2)
escreval("Idade:")
leia(idade2)

media <- (idade1 + idade2) / 2

escreva("A idade media de ", nome1 , " e ", nome2, "e de ", media, " anos ")


Fimalgoritmo